# Generated by Django 4.2.4 on 2023-08-17 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUser', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=100)),
                ('lastNAme', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('1', 'Administrador'), ('2', 'Validador'), ('3', 'Capturador')], default='3', max_length=1)),
            ],
        ),
    ]
