# Generated by Django 4.2.4 on 2023-08-17 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='lastNAme',
            new_name='Apellido',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Name',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='state',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='type',
            new_name='tipo',
        ),
    ]
