# Generated by Django 4.2.4 on 2023-08-21 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_rename_lastname_usuario_apellido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='Apellido',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Nombre',
            new_name='nombre',
        ),
    ]
