# Generated by Django 4.2.4 on 2023-08-24 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_paises'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoFuerza',
            fields=[
                ('idEdoFuerza', models.AutoField(primary_key=True, serialize=False)),
                ('oficinaR', models.CharField(max_length=50)),
                ('numPunto', models.IntegerField()),
                ('nomPuntoRevision', models.CharField(max_length=100)),
                ('tipoP', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=300)),
                ('coordenadasTexto', models.CharField(max_length=300)),
                ('latitud', models.FloatField(null=True)),
                ('longitud', models.FloatField(null=True)),
                ('personalINM', models.IntegerField()),
                ('personalSEDENA', models.IntegerField()),
                ('personalMarina', models.IntegerField()),
                ('personalGuardiaN', models.IntegerField()),
                ('personalOTROS', models.IntegerField()),
                ('vehiculos', models.IntegerField()),
                ('seccion', models.IntegerField()),
            ],
        ),
    ]
