# Generated by Django 4.2.4 on 2023-09-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_frases'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('idMunicipio', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=250)),
                ('estadoAbr', models.CharField(max_length=50)),
                ('nomMunicipio', models.CharField(max_length=250)),
            ],
        ),
    ]
