# Generated by Django 4.2.4 on 2023-09-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_municipios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.IntegerField(choices=[('1', 'Administrador'), ('2', 'Validador'), ('3', 'Capturador')], default=1),
        ),
    ]
