# Generated by Django 4.2.4 on 2023-09-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0014_rescatepunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescatepunto',
            name='empresa',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='rescatepunto',
            name='lineaAutobus',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='rescatepunto',
            name='municipio',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='rescatepunto',
            name='nombreHotel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='rescatepunto',
            name='numeroEcono',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='rescatepunto',
            name='placas',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='rescatepunto',
            name='puntoEstra',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='rescatepunto',
            name='tipoVehic',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
