# Generated by Django 4.2.4 on 2023-09-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0015_alter_rescatepunto_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescatepunto',
            name='numFamilia',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='rescatepunto',
            name='parentesco',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
