# Generated by Django 4.2.4 on 2023-09-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0016_alter_rescatepunto_numfamilia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteoRapidoPunto',
            fields=[
                ('IdRescateR', models.AutoField(primary_key=True, serialize=False)),
                ('oficinaRepre', models.CharField(max_length=50)),
                ('fecha', models.CharField(max_length=10)),
                ('hora', models.CharField(max_length=5)),
                ('aeropuerto', models.BooleanField(default=False)),
                ('carretero', models.BooleanField(default=False)),
                ('tipoVehic', models.CharField(blank=True, max_length=30)),
                ('lineaAutobus', models.CharField(blank=True, max_length=50)),
                ('numeroEcono', models.CharField(blank=True, max_length=50)),
                ('placas', models.CharField(blank=True, max_length=20)),
                ('vehiculoAseg', models.BooleanField(default=False)),
                ('casaSeguridad', models.BooleanField(default=False)),
                ('centralAutobus', models.BooleanField(default=False)),
                ('ferrocarril', models.BooleanField(default=False)),
                ('empresa', models.CharField(blank=True, max_length=150)),
                ('hotel', models.BooleanField(default=False)),
                ('nombreHotel', models.CharField(blank=True, max_length=100)),
                ('puestosADispo', models.BooleanField(default=False)),
                ('juezCalif', models.BooleanField(default=False)),
                ('reclusorio', models.BooleanField(default=False)),
                ('policiaFede', models.BooleanField(default=False)),
                ('dif', models.BooleanField(default=False)),
                ('policiaEsta', models.BooleanField(default=False)),
                ('policiaMuni', models.BooleanField(default=False)),
                ('guardiaNaci', models.BooleanField(default=False)),
                ('fiscalia', models.BooleanField(default=False)),
                ('otrasAuto', models.BooleanField(default=False)),
                ('voluntarios', models.BooleanField(default=False)),
                ('otro', models.BooleanField(default=False)),
                ('presuntosDelincuentes', models.BooleanField(default=False)),
                ('numPresuntosDelincuentes', models.IntegerField()),
                ('municipio', models.CharField(blank=True, max_length=200)),
                ('puntoEstra', models.CharField(blank=True, max_length=250)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('iso3', models.CharField(max_length=3)),
                ('AS_hombres', models.IntegerField()),
                ('AS_mujeresNoEmb', models.IntegerField()),
                ('AS_mujeresEmb', models.IntegerField()),
                ('nucleosFamiliares', models.IntegerField()),
                ('AA_hombres', models.IntegerField()),
                ('AA_mujeresNoEmb', models.IntegerField()),
                ('AA_mujeresEmb', models.IntegerField()),
                ('NNA_A_hombres', models.IntegerField()),
                ('NNA_A_mujeresNoEmb', models.IntegerField()),
                ('NNA_A_mujeresEmb', models.IntegerField()),
                ('NNA_S_hombres', models.IntegerField()),
                ('NNA_S_mujeresNoEmb', models.IntegerField()),
                ('NNA_S_mujeresEmb', models.IntegerField()),
            ],
        ),
    ]
